export const GET_QUIZZES = 'GET_QUIZZES';
export const GET_QUIZ_QUESTIONS = 'GET_QUIZ_QUESTIONS';
export const GET_QUESTION_ANSWERS = 'GET_QUESTION_ANSWERS';
export const SET_INITIAL_VALUES = 'SET_INITIAL_VALUES';
export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
export const SET_QUIZ_FINISHED = 'SET_QUIZ_FINISHED';
export const GET_QUIZ_RESULTS = 'GET_QUIZ_RESULTS';